#
# Build stage
#
FROM ubuntu:latest AS build
RUN apt-get update
RUN apt-get install openjdk-17-jdk -y
COPY . .
RUN ./gradlew bootjar --no-daemon

#
# Package stage
#
FROM openjdk:17-jdk-slim
COPY --from=build /target/hum-0.0.1-SNAPSHOT.jar demo.jar
# ENV PORT=8080
EXPOSE 7890
ENTRYPOINT ["java","-jar","demo.jar"]